[package]
name = "todo-rust"
version = "0.1.0"
authors = ["Seth Lowie <slowie@powerchordsystem.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
postgres = "0.15.2"
serde = "1.0.90"
serde_derive = "1.0.90"
